#!/bin/bash

# shellcheck source=common
. "${BASH_SOURCE%/*}/common"

COMMAND="(\
  echo $'<<< <<< <<<' && \
  ./script/ci && \
  echo $'\n>>> >>> >>>' \
)"

if command -v watchexec > /dev/null; then
  watchexec --debounce 250 \
            --ignore src/test/$LIB/Introduction.ml \
            --ignore src/test/$LIB/Signature.ml \
            -- "$COMMAND"
else
  >&2 echo "WARNING: Could not find suitable file watcher."
  exit 1
fi
